version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/arun0009lib"
    schedule:
      interval: "daily"
      day: "friday"
    groups:
      gradle-all:
        patterns: ["*"]

  - package-ecosystem: "gradle"
    directory: "/aws-powertools"
    schedule:
      interval: "daily"
      day: "friday"
    groups:
      gradle-all:
        patterns: ["*"]

  - package-ecosystem: "docker"
    directory: "/arun0009lib"
    schedule:
      interval: "daily"
      day: "friday"
    groups:
      docker-all:
        patterns: ["*"]

  - package-ecosystem: "docker-compose"
    directory: "/arun0009lib"
    schedule:
      interval: "daily"
      day: "friday"
    groups:
      compose-all:
        patterns: ["*"]

